[build]
  command = "npm install --prefix frontend && npm run build --prefix frontend"

# Redirect with a 200 for api
[[redirects]]
  from = "/api/*"
  to = "https://mern-ecommerce-g8bh.onrender.com/api/:splat"
  status = 200

# Redirect with a 200
[[redirects]]
  from = "/*"
 to = "/"
 status = 200