[build]
  command = "npm install --prefix frontend && npm run build --prefix frontend"

# Redirect with a 301
[[redirects]]
  from = "/api/*"
  to = "https://mern-ecommerce-g8bh.onrender.com/api/:splat"
  status = 301

# Redirect with a 200
[[redirects]]
  from = "/*"
  to = "index.html"
  status = 200